<?php

/**
 * @file
 * Primary module hooks for Islands module.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_page_attachments().
 */
function islands_page_attachments(array &$attachments) {
  $metadata = BubbleableMetadata::createFromRenderArray($attachments);

  /** @var \Drupal\Core\Extension\ThemeHandlerInterface $themeHandler */
  $themeHandler = \Drupal::service('theme_handler');
  $themes = $themeHandler->listInfo();

  $modules = \Drupal::moduleHandler()->getModuleList();
  $sources = array_merge($modules, $themes);

  /** @var \Drupal\Core\File\FileSystemInterface $file_system */
  $file_system = \Drupal::service('file_system');
  $islands = [];

  // Review themes and modules to find *.island.* files
  foreach ($sources as $source) {
    $path = $source->getPath();
    $directory = $path . '/templates';
    $name = $source->getName();
    if (is_dir($directory)) {
      $island_files = $file_system->scanDirectory($directory, '/.*\.island.*$/');
      foreach ($island_files as $island_file) {
        $islands[$name . '/' . $island_file->filename] = '/' . $island_file->uri;
      }
    }
  }

  // Generate an import map for the islands
  // Borrowed with kudos from https://www.drupal.org/project/importmap
  $metadata->addAttachments([
    'html_head' => [
      [
        [
          '#tag' => 'script',
          '#attributes' => ['type' => 'importmap'],
          '#value' => Json::encode(
            [
              'imports' => $islands,
            ]
          ),
          '#weight' => 0,
        ],
        'islands_json',
      ],
    ],
  ]);

  $metadata->applyTo($attachments);
}
